#Spring settings:
spring.application.name=accessing-data-mysql
#With XAMPP
#spring.datasource.url=jdbc:mysql://localhost:3306/cinesdb
#spring.datasource.url=jdbc:mysql://localhost:3307/cinesdb
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Como te decía el log, esto ya no hace falta ponerlo a mano, pero si lo pones, que sea el de Postgres:
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#With PostGreSQL:
spring.datasource.url=jdbc:postgresql://localhost:5432/dutching_db
spring.datasource.username=postgres
spring.datasource.password=postgre


#With MongoDB
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb://localhost:27017/cinesdb
#server.port=8080

#JPA Hibernate Settings:
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#To connect to a Eureka Server:
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.com.services-url.defaultZone=http://localhost:9096/eureka/
eureka.instance.hostname=localhost

# For com.connection to Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
# App route if necessary
springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.pathsToMatch=restapi/v2/**
# Title and description of the API
#springdoc.api-docs.title=CineDB
#springdoc.api-docs.version=1.0.0
